### ISSUE TITLE
How to generate point cloud data?

### ISSUE THREAD

**Issue by LZL-CS** [sijieaaa/HypLiLoc#1]
Hi, thanks for your excellent work. 

May I know how you build .npy point cloud data in the folder **velodyne_left_fps_4096_3_float32_npy** you provided?  BTW, it seems that you down-sample each frame of point cloud to 4096 points, may I know what method you used  for that?

I appreciate any help you can provide.

**Comment by sijieaaa** [comment]
Hi,

We use farthest point sampling to downsample them.

Thanks.
