### ISSUE TITLE
Asking about required GPU memory

### ISSUE THREAD

**Issue by sunnyHelen** [sijieaaa/HypLiLoc#2]
Hi, thanks a lot for sharing your great work. I would like to know the required GPU memory for this work to decide if my device can support my further exploration. Thanks for your help.

Best

**Comment by sijieaaa** [comment]
Hi, I think a 24GB GPU (3090/a5000/4090) is enough in this work.

**Comment by sunnyHelen** [comment]
Thanks a lot for your reply.
