### ISSUE TITLE
Question about point cloud normalization

### ISSUE THREAD

**Issue by LZL-CS** [sijieaaa/HypLiLoc#3]
Hi @sijieaaa, 

I downloaded the point cloud data you provided and checked the values (x, y, z) are within the range of [-1,1]. May I know how did you normalize the point cloud data? 

I appreciate any help you can provide.

**Comment by sijieaaa** [comment]
Hi,

We do not normalize the point cloud data.

**Comment by sijieaaa** [comment]
The provided point cloud data is not normalized into [-1,1]. Most necessary data processing is included in `data/robotcar.py`.
