### ISSUE TITLE
Why does the network can predict the global pose with only lidar input?

### ISSUE THREAD

**Issue by Zhenghao97** [sijieaaa/HypLiLoc#4]
Hi, thanks for your great work~

In the introduction of the paper, there is a sentence called "During inference, taking the LiDAR scan as input, the pose regression network directly regresses the global pose without any pre-constructed candidate database or map." I don't understand this.

When people want to estimate their position, they usually collect what they see from the environment and a map or other something. I don't know without the map, how does the network estimate the global pose.

Looking forward for your reply, appreciate it~

**Comment by sijieaaa** [comment]
Hi,

You can treat the regression-based pose estimation network as a "memorizer", where this network can **implicitly** memorize "LiDAR scan - pose" pairs. Therefore, when inputting LiDAR scans, the network can directly output the corresponding pose. Indeed, the drawback of doing this is that regression networks lack generalization ability. When some new-place LiDAR scan comes in, the network cannot output the new pose correctly.

By comparison, traditional pose estimation pipelines usually **explicitly** store a "LiDAR scan - pose" database, which is the biggest difference from regression-based pose networks.
