### ISSUE TITLE
Projection Feature Extraction

### ISSUE THREAD

**Issue by Nulizainuli** [sijieaaa/HypLiLoc#5]
Hello, great work. Could you please let me know if your code includes a method for projecting point clouds into images?

**Comment by sijieaaa** [comment]
Thanks for the question. We do not include the projection method in our codes.

**Comment by Nulizainuli** [comment]
Hello, thank you for your response. May I kindly ask if you could provide the code related to projecting point clouds into images, as well as let me know if any processing has been applied to the projected images? Thank you, and I look forward to your reply.
