### ISSUE TITLE
The number of point cloud points and the size of the projected image.

### ISSUE THREAD

**Issue by Nulizainuli** [sijieaaa/HypLiLoc#6]
Hello, great job, congratulations! I would like to ask whether the point cloud has been downsampled. If so, what is the number of points after downsampling? Also, what is the size of the projected image? If it's convenient, please let me know. Thank you very much!

**Comment by sijieaaa** [comment]
I don't remember the exact parameters. All information is provided in codes. When you reproduce this repo, you can know details.

**Comment by Nulizainuli** [comment]
think you for your answer.
